name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: awojasinski:stm32_cmake-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      run: |
        cmake -B ./build -S . -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-m4.cmake
        cmake --build ./build --parallel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          build/bin
          build/app/*.map
        retention-days: 7
